spring:
  datasource:
    # 注意设置useSSL
    url: jdbc:mysql://localhost:3306/java_st?useSSL=false
    username: root
    password: lyt5217199
    driver-class-name: com.mysql.jdbc.Driver

# mybatis 配置内容
mybatis:
  config-location: classpath:mybatis-config.xml # 配置 MyBatis 配置文件路径
  mapper-locations: classpath:mapper/*.xml # 配置 Mapper XML 地址
  type-aliases-package: com.example.lab2_mybatis_mysql.dto # 配置数据库实体包路径