spring:
  datasource:
    # 注意设置useSSL
    url: jdbc:mysql://localhost:3306/java_st?useSSL=false
    username: root
    password: lyt5217199
    driver-class-name: com.mysql.jdbc.Driver

# mybatis-plus 配置内容
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
  global-config:
    db-config:
      id-type: auto # ID 主键自增
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.lab3_mybatis_plus_mysql.dto

logging:
  level:
    com:
      example:
        lab3_mybatis_plus_mysql:
          mapper: debug